materials:
  - name: "gold"
    normal: "content\\textures\\gold\\gold_normal.dds"
    baseColor: "content\\textures\\gold\\gold_base_color.dds"
    smoothness: "content\\textures\\gold\\gold_smoothness.dds"
    metalMask: "content\\textures\\gold\\gold_metal_mask.dds"
    reflectance: "content\\textures\\gold\\gold_reflectance.dds"
  - name: "aluminium"
    normal: "content\\textures\\aluminium\\aluminium_normal.dds"
    baseColor: "content\\textures\\aluminium\\aluminium_base_color.dds"
    smoothness: "content\\textures\\aluminium\\aluminium_smoothness.dds"
    metalMask: "content\\textures\\aluminium\\aluminium_metal_mask.dds"
    reflectance: "content\\textures\\aluminium\\aluminium_reflectance.dds"