materials:
  - name: "gold"
    normal: "content\\textures\\gold\\gold_normal.dds"
    baseColor: "content\\textures\\gold\\gold_base_color.dds"
    smoothness: "content\\textures\\gold\\gold_smoothness.dds"
    metalMask: "content\\textures\\gold\\gold_metal_mask.dds"
    reflectance: "content\\textures\\gold\\gold_reflectance.dds"
  - name: "aluminium"
    normal: "content\\textures\\aluminium\\aluminium_normal.dds"
    baseColor: "content\\textures\\aluminium\\aluminium_base_color.dds"
    smoothness: "content\\textures\\aluminium\\aluminium_smoothness.dds"
    metalMask: "content\\textures\\aluminium\\aluminium_metal_mask.dds"
    reflectance: "content\\textures\\aluminium\\aluminium_reflectance.dds"
  - name: "terracota"
    normal: "content\\textures\\terracota\\terracota_normal.dds"
    baseColor: "content\\textures\\terracota\\terracota_base_color.dds"
    smoothness: "content\\textures\\terracota\\terracota_smoothness.dds"
    metalMask: "content\\textures\\terracota\\terracota_metal_mask.dds"
    reflectance: "content\\textures\\terracota\\terracota_reflectance.dds"
  - name: "wood1"
    normal: "content\\textures\\wood1\\wood1_normal.dds"
    baseColor: "content\\textures\\wood1\\wood1_base_color.dds"
    smoothness: "content\\textures\\wood1\\wood1_smoothness.dds"
    metalMask: "content\\textures\\wood1\\wood1_metal_mask.dds"
    reflectance: "content\\textures\\wood1\\wood1_reflectance.dds"
  - name: "mossy_stone"
    normal: "content\\textures\\mossy_stone\\mossy_stone_normal.dds"
    baseColor: "content\\textures\\mossy_stone\\mossy_stone_base_color.dds"
    smoothness: "content\\textures\\mossy_stone\\mossy_stone_smoothness.dds"
    metalMask: "content\\textures\\mossy_stone\\mossy_stone_metal_mask.dds"
    reflectance: "content\\textures\\mossy_stone\\mossy_stone_reflectance.dds"
  - name: "silver"
    normal: "content\\textures\\silver\\silver_normal.dds"
    baseColor: "content\\textures\\silver\\silver_base_color.dds"
    smoothness: "content\\textures\\silver\\silver_smoothness.dds"
    metalMask: "content\\textures\\silver\\silver_metal_mask.dds"
    reflectance: "content\\textures\\silver\\silver_reflectance.dds"
  - name: "platinum"
    normal: "content\\textures\\platinum\\platinum_normal.dds"
    baseColor: "content\\textures\\platinum\\platinum_base_color.dds"
    smoothness: "content\\textures\\platinum\\platinum_smoothness.dds"
    metalMask: "content\\textures\\platinum\\platinum_metal_mask.dds"
    reflectance: "content\\textures\\platinum\\platinum_reflectance.dds"