models:
  - renderType: Normal_Displacement
    path: "content\\models\\plane.obj"
    translation: [0.0, -500.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scaling: [11100.0, 11100.0, 11100.0]
    textureScaleFactor: 10.0
    material: "silver"
    normalMapTexture: "content\\textures\\rock1\\rock1_normal.dds"
    displacementMapTexture: "content\\textures\\rock1\\rock1_height.dds"
    edgeTessellationFactors: [40.0, 40.0, 40.0]
    insideTessellationFactors: 1.0
    displacementScale: 100.0
  - renderType: Normal_Displacement
    path: "content\\models\\plane.obj"
    translation: [0.0, 500.0, 0.0]
    rotation: [3.14, 0.0, 0.0]
    scaling: [1100.0, 1100.0, 1100.0]
    textureScaleFactor: 2.0
    material: "rock1"
    displacementMapTexture: "content\\textures\\rock1\\rock1_height.dds"
    edgeTessellationFactors: [10.0, 10.0, 10.0]
    insideTessellationFactors: 10.0
    displacementScale: 20.0
  - renderType: Normal_Displacement
    path: "content\\models\\plane.obj"
    translation: [0.0, 0.0, 500.0]
    rotation: [-1.57, 0.0, 0.0]
    scaling: [1100.0, 1100.0, 1100.0]
    textureScaleFactor: 2.0
    material: "rock1"
    displacementMapTexture: "content\\textures\\rock1\\rock1_height.dds"
    edgeTessellationFactors: [10.0, 10.0, 10.0]
    insideTessellationFactors: 10.0
    displacementScale: 20.0
  - renderType: Normal_Displacement
    path: "content\\models\\plane.obj"
    translation: [500.0, 0.0, 0.0]
    rotation: [1.57, -1.57, 0.0]
    scaling: [1100.0, 1100.0, 1100.0]   
    textureScaleFactor: 2.0
    material: "rock1"
    displacementMapTexture: "content\\textures\\rock1\\rock1_height.dds"
    edgeTessellationFactors: [10.0, 10.0, 10.0]
    insideTessellationFactors: 10.0
    displacementScale: 20.0
  - renderType: Normal_Displacement
    path: "content\\models\\plane.obj"
    translation: [-500.0, 0.0, 0.0]
    rotation: [1.57, 1.57, 0.0]
    scaling: [1100.0, 1100.0, 1100.0] 
    textureScaleFactor: 2.0
    material: "rock1" 
    displacementMapTexture: "content\\textures\\rock1\\rock1_height.dds"
    edgeTessellationFactors: [10.0, 10.0, 10.0]
    insideTessellationFactors: 10.0
    displacementScale: 20.0
  - renderType: Basic
    path: "content\\models\\mitsuba-sphere.obj"
    translation: [0.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scaling: [80.0, 80.0, 80.0]
    material: "platinum"
  - renderType: Basic
    path: "content\\models\\mitsuba-sphere.obj"
    translation: [250.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scaling: [80.0, 80.0, 80.0]
    material: "gold"
  - renderType: Normal_Displacement
    path: "content\\models\\mitsuba-sphere.obj"
    translation: [-250.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scaling: [80.0, 80.0, 80.0]
    textureScaleFactor: 1.0
    material: "rock1"
    displacementMapTexture: "content\\textures\\rock1\\rock1_height.dds"
    edgeTessellationFactors: [4.0, 4.0, 4.0]
    insideTessellationFactors: 4.0
    displacementScale: 8.0