models:
  - renderType: Basic
    path: "content\\models\\mitsuba.obj" 
    translation: [0.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scaling: [40.0, 40.0, 40.0] 
    material: "bronze"
  - renderType: Basic
    path: "content\\models\\mitsuba.obj"
    translation: [500.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scaling: [40.0, 40.0, 40.0] 
    material: "gold"
  - renderType: Basic
    path: "content\\models\\mitsuba.obj" 
    translation: [1000.0, 0.0, 0.0] 
    rotation: [0.0, 0.0, 0.0]
    scaling: [40.0, 40.0, 40.0]  
    material: "iron"
  - renderType: Basic
    path: "content\\models\\mitsuba.obj"
    translation: [1500.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scaling: [40.0, 40.0, 40.0] 
    material: "silver"
  - renderType: Basic
    path: "content\\models\\mitsuba.obj"
    translation: [2000.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scaling: [40.0, 40.0, 40.0]  
    material: "titanium"
  - renderType: Normal_Displacement
    path: "content\\models\\mitsuba.obj"
    translation: [-500.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scaling: [40.0, 40.0, 40.0] 
    textureScaleFactor: 1.0
    material: "muddy_dirt" 
    normalMapTexture: "content\\materials\\muddy_dirt\\muddy_dirt_normal.dds"
    displacementMapTexture: "content\\materials\\muddy_dirt\\muddy_dirt_height.dds"
    tessellationFactor: 5.0
    displacementScale: 3.0
  - renderType: Normal_Displacement 
    path: "content\\models\\mitsuba.obj"
    translation: [-1000.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scaling: [1.0, 1.0, 1.0] 
    textureScaleFactor: 1.0
    material: "rock1" 
    normalMapTexture: "content\\materials\\rock1\\rock1_normal.dds"
    displacementMapTexture: "content\\materials\\rock1\\rock1_height.dds"
    tessellationFactor: 5.0
    displacementScale: 3.0
  - renderType: Normal_Displacement
    path: "content\\models\\mitsuba.obj"
    translation: [-1500.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scaling: [40.0, 40.0, 40.0] 
    textureScaleFactor: 1.0
    material: "stone1"  
    normalMapTexture: "content\\materials\\stone1\\stone1_normal.dds"
    displacementMapTexture: "content\\materials\\stone1\\stone1_height.dds"
    tessellationFactor: 5.0
    displacementScale: 5.0
  - renderType: Normal
    path: "content\\models\\mitsuba.obj"
    translation: [-2000.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scaling: [40.0, 40.0, 40.0] 
    textureScaleFactor: 1.0
    material: "concrete1"  
    normalMapTexture: "content\\materials\\concrete1\\concrete1_normal.dds"
    displacementMapTexture: "content\\materials\\concrete1\\concrete1_height.dds"
    tessellationFactor: 5.0
    displacementScale: 5.0
