models:
  - renderType: Normal_Displacement
    path: "content\\models\\plane.obj"
    translation: [0.0, -500.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scaling: [1500.0, 1500.0, 1500.0]  
    diffuseMapTexture: "content\\textures\\brick1_diffuse.dds"
    normalMapTexture: "content\\textures\\brick1_normal.dds"
    specularMapTexture: "content\\textures\\brick1_specular.dds"
    displacementMapTexture: "content\\textures\\brick1_height.dds"
    edgeTesselationFactors: [5.0, 5.0, 5.0]
    insideTessellationFactors: 5.0
    displacementScale: 10.0
  - renderType: Normal_Displacement
    path: "content\\models\\plane.obj"
    translation: [0.0, 500.0, 0.0]
    rotation: [3.14, 0.0, 0.0]
    scaling: [1500.0, 1500.0, 1500.0]  
    diffuseMapTexture: "content\\textures\\brick1_diffuse.dds"
    normalMapTexture: "content\\textures\\brick1_normal.dds"
    specularMapTexture: "content\\textures\\brick1_specular.dds"
    displacementMapTexture: "content\\textures\\brick1_height.dds"
    edgeTesselationFactors: [5.0, 5.0, 5.0]
    insideTessellationFactors: 5.0
    displacementScale: 10.0
  - renderType: Normal_Displacement
    path: "content\\models\\plane.obj"
    translation: [0.0, 0.0, 500.0]
    rotation: [-1.57, 0.0, 0.0]
    scaling: [1500.0, 1500.0, 1500.0]  
    diffuseMapTexture: "content\\textures\\brick1_diffuse.dds"
    normalMapTexture: "content\\textures\\brick1_normal.dds"
    specularMapTexture: "content\\textures\\brick1_specular.dds"
    displacementMapTexture: "content\\textures\\brick1_height.dds"
    edgeTesselationFactors: [5.0, 5.0, 5.0]
    insideTessellationFactors: 5.0
    displacementScale: 10.0
  - renderType: Normal_Displacement
    path: "content\\models\\plane.obj"
    translation: [400.0, 0.0, 0.0]
    rotation: [1.57, -1.57, 0.0]
    scaling: [1500.0, 1500.0, 1500.0]  
    diffuseMapTexture: "content\\textures\\brick1_diffuse.dds"
    normalMapTexture: "content\\textures\\brick1_normal.dds"
    specularMapTexture: "content\\textures\\brick1_specular.dds"
    displacementMapTexture: "content\\textures\\brick1_height.dds"
    edgeTesselationFactors: [5.0, 5.0, 5.0]
    insideTessellationFactors: 5.0
    displacementScale: 10.0
  - renderType: Normal_Displacement
    path: "content\\models\\plane.obj"
    translation: [-500.0, 0.0, 0.0]
    rotation: [1.57, 1.57, 0.0]
    scaling: [1500.0, 1500.0, 1500.0]  
    diffuseMapTexture: "content\\textures\\brick1_diffuse.dds"
    normalMapTexture: "content\\textures\\brick1_normal.dds"
    specularMapTexture: "content\\textures\\brick1_specular.dds"
    displacementMapTexture: "content\\textures\\brick1_height.dds"
    edgeTesselationFactors: [5.0, 5.0, 5.0]
    insideTessellationFactors: 5.0
    displacementScale: 10.0
  - renderType: Normal
    path: "content\\models\\torusKnot.obj"
    translation: [0.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scaling: [450.0, 450.0, 450.0]    
    diffuseMapTexture: "content\\textures\\white_diffuse.dds"
    normalMapTexture: "content\\textures\\white_normal.dds"
    specularMapTexture: "content\\textures\\white_specular.dds"
    displacementMapTexture: "content\\textures\\white_height.dds"
    edgeTesselationFactors: [2.0, 2.0, 2.0]
    insideTessellationFactors: 1.0
    displacementScale: 2.0