models:
  - renderType: Normal_Displacement
    path: "content\\models\\plane.obj"
    translation: [0.0, -500.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scaling: [1100.0, 1100.0, 1100.0]
    textureScaleFactor: 2.0	
    material: "gold"
    displacementMapTexture: "content\\textures\\rock1_height.dds"
    normalMapTexture: "content\\textures\\rock1_normal.dds"
    edgeTesselationFactors: [64.0, 64.0, 64.0]
    insideTessellationFactors: 64.0
    displacementScale: 20.0
  - renderType: Normal_Displacement
    path: "content\\models\\plane.obj"
    translation: [0.0, 500.0, 0.0]
    rotation: [3.14, 0.0, 0.0]
    scaling: [1100.0, 1100.0, 1100.0]
    textureScaleFactor: 2.0
    material: "gold"
    displacementMapTexture: "content\\textures\\rock1_height.dds"
    normalMapTexture: "content\\textures\\rock1_normal.dds"
    edgeTesselationFactors: [64.0, 64.0, 64.0]
    insideTessellationFactors: 64.0
    displacementScale: 20.0
  - renderType: Normal_Displacement
    path: "content\\models\\plane.obj"
    translation: [0.0, 0.0, 500.0]
    rotation: [-1.57, 0.0, 0.0]
    scaling: [1100.0, 1100.0, 1100.0]
    textureScaleFactor: 2.0
    material: "gold"
    displacementMapTexture: "content\\textures\\rock1_height.dds"
    normalMapTexture: "content\\textures\\rock1_normal.dds"
    edgeTesselationFactors: [64.0, 64.0, 64.0]
    insideTessellationFactors: 64.0
    displacementScale: 20.0
  - renderType: Normal_Displacement
    path: "content\\models\\plane.obj"
    translation: [500.0, 0.0, 0.0]
    rotation: [1.57, -1.57, 0.0]
    scaling: [1100.0, 1100.0, 1100.0]   
    textureScaleFactor: 2.0
    material: "aluminium"
    displacementMapTexture: "content\\textures\\rock1_height.dds"
    normalMapTexture: "content\\textures\\rock1_normal.dds"
    edgeTesselationFactors: [64.0, 64.0, 64.0]
    insideTessellationFactors: 64.0
    displacementScale: 20.0
  - renderType: Normal_Displacement
    path: "content\\models\\plane.obj"
    translation: [-500.0, 0.0, 0.0]
    rotation: [1.57, 1.57, 0.0]
    scaling: [1100.0, 1100.0, 1100.0] 
    textureScaleFactor: 2.0
    material: "aluminium"
    displacementMapTexture: "content\\textures\\rock1_height.dds"
    normalMapTexture: "content\\textures\\rock1_normal.dds"
    edgeTesselationFactors: [64.0, 64.0, 64.0]
    insideTessellationFactors: 64.0
    displacementScale: 20.0
  - renderType: Basic
    path: "content\\models\\bunny.obj"
    translation: [-200.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scaling: [150.0, 150.0, 150.0]
    material: "gold"
  - renderType: Basic
    path: "content\\models\\bunny.obj"
    translation: [200.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scaling: [150.0, 150.0, 150.0]
    material: "aluminium"