models:
  - renderType: Normal_Displacement
    path: "content\\models\\plane.obj"
    translation: [0.0, -500.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scaling: [1100.0, 1100.0, 1100.0]
    textureScaleFactor: 2.0	
    diffuseMapTexture: "content\\textures\\rock1_diffuse.dds"
    normalMapTexture: "content\\textures\\rock1_normal.dds"
    specularMapTexture: "content\\textures\\rock1_specular.dds"
    displacementMapTexture: "content\\textures\\rock1_height.dds"
    edgeTesselationFactors: [64.0, 64.0, 64.0]
    insideTessellationFactors: 64.0
    displacementScale: 20.0
  - renderType: Normal_Displacement
    path: "content\\models\\plane.obj"
    translation: [0.0, 500.0, 0.0]
    rotation: [3.14, 0.0, 0.0]
    scaling: [1100.0, 1100.0, 1100.0]
    textureScaleFactor: 2.0	
    diffuseMapTexture: "content\\textures\\rock1_diffuse.dds"
    normalMapTexture: "content\\textures\\rock1_normal.dds"
    specularMapTexture: "content\\textures\\rock1_specular.dds"
    displacementMapTexture: "content\\textures\\rock1_height.dds"
    edgeTesselationFactors: [64.0, 64.0, 64.0]
    insideTessellationFactors: 64.0
    displacementScale: 20.0
  - renderType: Normal_Displacement
    path: "content\\models\\plane.obj"
    translation: [0.0, 0.0, 500.0]
    rotation: [-1.57, 0.0, 0.0]
    scaling: [1100.0, 1100.0, 1100.0]
    textureScaleFactor: 2.0	
    diffuseMapTexture: "content\\textures\\rock1_diffuse.dds"
    normalMapTexture: "content\\textures\\rock1_normal.dds"
    specularMapTexture: "content\\textures\\rock1_specular.dds"
    displacementMapTexture: "content\\textures\\rock1_height.dds"
    edgeTesselationFactors: [64.0, 64.0, 64.0]
    insideTessellationFactors: 64.0
    displacementScale: 20.0
  - renderType: Normal_Displacement
    path: "content\\models\\plane.obj"
    translation: [500.0, 0.0, 0.0]
    rotation: [1.57, -1.57, 0.0]
    scaling: [1100.0, 1100.0, 1100.0]   
    textureScaleFactor: 2.0
    diffuseMapTexture: "content\\textures\\rock1_diffuse.dds"
    normalMapTexture: "content\\textures\\rock1_normal.dds"
    specularMapTexture: "content\\textures\\rock1_specular.dds"
    displacementMapTexture: "content\\textures\\rock1_height.dds"
    edgeTesselationFactors: [64.0, 64.0, 64.0]
    insideTessellationFactors: 64.0
    displacementScale: 20.0
  - renderType: Normal_Displacement
    path: "content\\models\\plane.obj"
    translation: [-500.0, 0.0, 0.0]
    rotation: [1.57, 1.57, 0.0]
    scaling: [1100.0, 1100.0, 1100.0] 
    textureScaleFactor: 2.0	
    diffuseMapTexture: "content\\textures\\rock1_diffuse.dds"
    normalMapTexture: "content\\textures\\rock1_normal.dds"
    specularMapTexture: "content\\textures\\rock1_specular.dds"
    displacementMapTexture: "content\\textures\\rock1_height.dds"
    edgeTesselationFactors: [64.0, 64.0, 64.0]
    insideTessellationFactors: 64.0
    displacementScale: 20.0
  - renderType: Normal
    path: "content\\models\\torusKnot.obj"
    translation: [0.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scaling: [450.0, 450.0, 450.0]   
    textureScaleFactor: 1.0	
    diffuseMapTexture: "content\\textures\\white_diffuse.dds"
    normalMapTexture: "content\\textures\\torusKnot_normal.dds"
    specularMapTexture: "content\\textures\\torusKnot_specular.dds"