models:
  - renderType: Normal
    path: "content\\models\\sponza.obj"
    translation: [0.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    scaling: [1.0, 1.0, 1.0] 
    textureScaleFactor: 2.0
    material: "gold" 
    normalMapTexture: "content\\textures\\rock1\\rock1_normal.dds"
    displacementMapTexture: "content\\textures\\rock1\\rock1_height.dds"
    edgeTessellationFactors: [5.0, 5.0, 5.0]
    insideTessellationFactors: 5.0
    displacementScale: 5.0