materials:
  - name: "bronze"
    normal: "content\\materials\\bronze\\bronze_normal.dds"
    baseColor: "content\\materials\\bronze\\bronze_base_color.dds"
    smoothness: "content\\materials\\bronze\\bronze_smoothness.dds" 
    metalMask: "content\\materials\\bronze\\bronze_metal_mask.dds"
    curvature: "content\\materials\\bronze\\bronze_curvature.dds"
  - name: "concrete1"
    normal: "content\\materials\\concrete1\\concrete1_normal.dds"
    baseColor: "content\\materials\\concrete1\\concrete1_base_color.dds"
    smoothness: "content\\materials\\concrete1\\concrete1_smoothness.dds" 
    metalMask: "content\\materials\\concrete1\\concrete1_metal_mask.dds"
    curvature: "content\\materials\\concrete1\\concrete1_curvature.dds"
  - name: "copper"
    normal: "content\\materials\\copper\\copper_normal.dds"
    baseColor: "content\\materials\\copper\\copper_base_color.dds"
    smoothness: "content\\materials\\copper\\copper_smoothness.dds" 
    metalMask: "content\\materials\\copper\\copper_metal_mask.dds"
    curvature: "content\\materials\\copper\\copper_curvature.dds"
  - name: "gold"
    normal: "content\\materials\\gold\\gold_normal.dds"
    baseColor: "content\\materials\\gold\\gold_base_color.dds"
    smoothness: "content\\materials\\gold\\gold_smoothness.dds"
    metalMask: "content\\materials\\gold\\gold_metal_mask.dds"
    curvature: "content\\materials\\gold\\gold_curvature.dds"
  - name: "iron"
    normal: "content\\materials\\iron\\iron_normal.dds"
    baseColor: "content\\materials\\iron\\iron_base_color.dds"
    smoothness: "content\\materials\\iron\\iron_smoothness.dds"
    metalMask: "content\\materials\\iron\\iron_metal_mask.dds"
    curvature: "content\\materials\\iron\\iron_curvature.dds"
  - name: "muddy_dirt"
    normal: "content\\materials\\muddy_dirt\\muddy_dirt_normal.dds"
    baseColor: "content\\materials\\muddy_dirt\\muddy_dirt_base_color.dds"
    smoothness: "content\\materials\\muddy_dirt\\muddy_dirt_smoothness.dds"
    metalMask: "content\\materials\\muddy_dirt\\muddy_dirt_metal_mask.dds"
    curvature: "content\\materials\\muddy_dirt\\muddy_dirt_curvature.dds"
  - name: "rock1"
    normal: "content\\materials\\rock1\\rock1_normal.dds"
    baseColor: "content\\materials\\rock1\\rock1_base_color.dds"
    smoothness: "content\\materials\\rock1\\rock1_smoothness.dds"
    metalMask: "content\\materials\\rock1\\rock1_metal_mask.dds"
    curvature: "content\\materials\\rock1\\rock1_curvature.dds"
  - name: "silver"
    normal: "content\\materials\\silver\\silver_normal.dds"
    baseColor: "content\\materials\\silver\\silver_base_color.dds"
    smoothness: "content\\materials\\silver\\silver_smoothness.dds"
    metalMask: "content\\materials\\silver\\silver_metal_mask.dds"
    curvature: "content\\materials\\silver\\silver_curvature.dds"
  - name: "stone1"
    normal: "content\\materials\\stone1\\stone1_normal.dds"
    baseColor: "content\\materials\\stone1\\stone1_base_color.dds"
    smoothness: "content\\materials\\stone1\\stone1_smoothness.dds"
    metalMask: "content\\materials\\stone1\\stone1_metal_mask.dds"
    curvature: "content\\materials\\stone1\\stone1_curvature.dds"
  - name: "titanium"
    normal: "content\\materials\\titanium\\titanium_normal.dds"
    baseColor: "content\\materials\\titanium\\titanium_base_color.dds"
    smoothness: "content\\materials\\titanium\\titanium_smoothness.dds"
    metalMask: "content\\materials\\titanium\\titanium_metal_mask.dds"
    curvature: "content\\materials\\titanium\\titanium_curvature.dds"