materials:
  - name: "bronze"
    normal: "content\\materials\\bronze\\bronze_normal.dds"
    baseColor: "content\\materials\\bronze\\bronze_base_color.dds"
    smoothness: "content\\materials\\bronze\\bronze_smoothness.dds" 
    metalMask: "content\\materials\\bronze\\bronze_metal_mask.dds"
    reflectance: "content\\materials\\bronze\\bronze_reflectance.dds"
  - name: "copper"
    normal: "content\\materials\\copper\\copper_normal.dds"
    baseColor: "content\\materials\\copper\\copper_base_color.dds"
    smoothness: "content\\materials\\copper\\copper_smoothness.dds" 
    metalMask: "content\\materials\\copper\\copper_metal_mask.dds"
    reflectance: "content\\materials\\copper\\copper_reflectance.dds"
  - name: "gold"
    normal: "content\\materials\\gold\\gold_normal.dds"
    baseColor: "content\\materials\\gold\\gold_base_color.dds"
    smoothness: "content\\materials\\gold\\gold_smoothness.dds"
    metalMask: "content\\materials\\gold\\gold_metal_mask.dds"
    reflectance: "content\\materials\\gold\\gold_reflectance.dds"
  - name: "iron"
    normal: "content\\materials\\iron\\iron_normal.dds"
    baseColor: "content\\materials\\iron\\iron_base_color.dds"
    smoothness: "content\\materials\\iron\\iron_smoothness.dds"
    metalMask: "content\\materials\\iron\\iron_metal_mask.dds"
    reflectance: "content\\materials\\iron\\iron_reflectance.dds"
  - name: "muddy_dirt"
    normal: "content\\materials\\muddy_dirt\\muddy_dirt_normal.dds"
    baseColor: "content\\materials\\muddy_dirt\\muddy_dirt_base_color.dds"
    smoothness: "content\\materials\\muddy_dirt\\muddy_dirt_smoothness.dds"
    metalMask: "content\\materials\\muddy_dirt\\muddy_dirt_metal_mask.dds"
    reflectance: "content\\materials\\muddy_dirt\\muddy_dirt_reflectance.dds"
  - name: "rock1"
    normal: "content\\materials\\rock1\\rock1_normal.dds"
    baseColor: "content\\materials\\rock1\\rock1_base_color.dds"
    smoothness: "content\\materials\\rock1\\rock1_smoothness.dds"
    metalMask: "content\\materials\\rock1\\rock1_metal_mask.dds"
    reflectance: "content\\materials\\rock1\\rock1_reflectance.dds"
  - name: "silver"
    normal: "content\\materials\\silver\\silver_normal.dds"
    baseColor: "content\\materials\\silver\\silver_base_color.dds"
    smoothness: "content\\materials\\silver\\silver_smoothness.dds"
    metalMask: "content\\materials\\silver\\silver_metal_mask.dds"
    reflectance: "content\\materials\\silver\\silver_reflectance.dds"
  - name: "titanium"
    normal: "content\\materials\\titanium\\titanium_normal.dds"
    baseColor: "content\\materials\\titanium\\titanium_base_color.dds"
    smoothness: "content\\materials\\titanium\\titanium_smoothness.dds"
    metalMask: "content\\materials\\titanium\\titanium_metal_mask.dds"
    reflectance: "content\\materials\\titanium\\titanium_reflectance.dds"